### ISSUE TITLE
Idea: Commandline support for sending config XML to execute

### ISSUE THREAD

**Issue by poorlymac** [gpx-animator/gpx-animator#546] opened 2023-06-16 22:44 UTC
Hi,

In the GUI you can saver and load the configuration XML, it would ease inter application integration if that XML could be sent on the commandline. e.g. java -jar gpx-animator.jar --run xyz.xml

CHEERS
Paul

**Comment by poorlymac** [comment] 2023-06-17 00:05
PR created !

**Comment by McPringle** [comment] 2023-06-17 15:04
This is a duplicate of #325 
Thank you very much for your PR!

**Closed by McPringle** 2023-06-17 15:04 UTC
Labels: duplicate
